### ISSUE TITLE
Typo - server/index.js, line 5

### ISSUE THREAD

**Issue by toporan** [adelowo/pusher-angular-realtime-feed#1]
This line points to "variables.env", but the file's name is **variable.env**
require('dotenv').config({ path: 'variable**s**.env' });

**Comment by adelowo** [comment]
Thanks a lot, @toporan .. I renamed the file to `variables.env`

https://github.com/adelowo/pusher-angular-realtime-feed/commit/019067b7ed4a67472d036b92d1870fd4daea399f
